services:
  db:
    image: mysql:8.0
    container_name: "mysql-database"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: openFoodFact
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306" # MySQL accessible sur le port 3306
    volumes:
      - ./mysql_data:/var/lib/mysql # Persistance des données MySQL
      - ./sql-scripts:/docker-entrypoint-initdb.d # Initialisation avec des scripts SQL au démarrage

volumes:
  mysql_data:
